### ISSUE TITLE
Share typo3conf local

### ISSUE THREAD

**Issue by topfender** [dkd/docker-typo3#1]
Is it possible to share typo3conf folder local as well by default?

**Comment by sascha-egerer** [comment]
I don't think that this would make sense. It only does if you are using this for development. You can simply adjust the docker-compose file and add the share or you can simply create your own image and use this Image as base image as described in the Readme.

**Comment by topfender** [comment]
Yes I want to use it for development. I'll try to use it as a base image, thanks.
