### ISSUE TITLE
DB_HOST not set

### ISSUE THREAD

**Issue by kraftb** [dkd/docker-typo3#2]
When I start this docker image and enter the container using:

```
docker exec -t -i typo3 /bin/bash
```

I can do "echo $DB_HOST" or "export" but the "DB_HOST" (and DB_PORT) variables are still set to **LinkMe** ... thus the getenv() in AdditionalConfiguration.php does not work and I can't access the TYPO3 installation.

When i do a "ps a x" inside the container I can see that the run-scripts are executed in the following fashion:

```
/bin/bash -c /run-typo3.sh && /run.sh
```

Sadly the "DB_HOST" and "DB_PORT" set in "run-typo3.sh" will not get exported to "run.sh" and thus to the apache process. I circumvented the problem by:
1. moving the "run.sh" script to a script named "run-apache.sh"
2. creating an empty (executable) "run.sh" script
3. Added a line `/run-apache.sh` at the end of run-typo3.sh

Can you confirm this issue? Or did I do something wrong?

**Comment by sascha-egerer** [comment]
Could you please explain how you start you container? I don't really understand your problem. The DB_PASS env varaible is missing in our docker command above...

You can also use the example docker-compose.yml file (`docker-compose up`). But you have to change the DB_PASS first in that file.

**Comment by kraftb** [comment]
I start the mysql server as described in your example but without the "-p 3306:3306" option as there is a mysql already running on my local machine - so I do not want the port to be mapped to localhost.

Then I start the "dkdde/typo3" container using the following command. I renamed the randomly given container name to "typo3"

docker run -d --link db:db -e DB_PASS="mysql" -p 8080:80 --name typo3 dkdde/typo3

As I mentioned the problem is not DB_PASS but DB_HOST and DB_PORT

**Comment by kraftb** [comment]
When I do an "echo getenv('DB_HOST'); exit();" in AdditionalConfiguration.php the value "*_LinkMe_" is shown. So the env var does not get replaced because of the issue described in my first posting: "&&" will not inherit any env vars set by a script running before it - even if the variables get exported.

**Comment by sascha-egerer** [comment]
Ah ok looks like you're right. Not sure why that has worked before. But to be honost - i would not use that image anymore as it's development is really inactive.

So +1 from me for your pull request for now...

**Comment by kraftb** [comment]
Are you planning to update it to 7.6? I guess everything which needs to be done is to change the dependency in the composer.json

**Comment by dkd-dobberkau** [comment]
yes, its on our to do list for january.
